/**
 * SquirrelDB TypeScript SDK - Cache (Redis-compatible)
 * Generated by sdk-generator v0.1.0
 * DO NOT EDIT MANUALLY
 */

export interface CacheOptions {
  host?: string;
  port?: number;
}

/**
 * Redis-compatible cache client using RESP protocol
 */
export class Cache {
  private socket!: ReturnType<typeof Bun.connect> extends Promise<infer T> ? T : never;
  private host: string;
  private port: number;
  private buffer = "";
  private pending: Array<{
    resolve: (value: unknown) => void;
    reject: (err: Error) => void;
  }> = [];

  private constructor(host: string, port: number) {
    this.host = host;
    this.port = port;
  }

  /**
   * Connect to cache server
   */
  static async connect(options: CacheOptions = {}): Promise<Cache> {
    const host = options.host ?? "localhost";
    const port = options.port ?? 6379;
    const cache = new Cache(host, port);
    await cache.connectInternal();
    return cache;
  }

  private async connectInternal(): Promise<void> {
    this.socket = await Bun.connect({
      hostname: this.host,
      port: this.port,
      socket: {
        data: (_, data) => {
          this.buffer += new TextDecoder().decode(data);
          this.processBuffer();
        },
        error: (_, err) => {
          const pending = this.pending.shift();
          if (pending) pending.reject(new Error(String(err)));
        },
        close: () => {},
        open: () => {},
      },
    });
  }

  private processBuffer(): void {
    while (this.buffer.length > 0 && this.pending.length > 0) {
      const result = this.parseResp();
      if (result === undefined) break;
      const pending = this.pending.shift();
      if (pending) pending.resolve(result);
    }
  }

  private parseResp(): unknown {
    if (this.buffer.length === 0) return undefined;
    const type = this.buffer[0];
    const newline = this.buffer.indexOf("\r\n");
    if (newline === -1) return undefined;

    switch (type) {
      case "+": {
        const value = this.buffer.slice(1, newline);
        this.buffer = this.buffer.slice(newline + 2);
        return value;
      }
      case "-": {
        const value = this.buffer.slice(1, newline);
        this.buffer = this.buffer.slice(newline + 2);
        throw new Error(value);
      }
      case ":": {
        const value = parseInt(this.buffer.slice(1, newline), 10);
        this.buffer = this.buffer.slice(newline + 2);
        return value;
      }
      case "$": {
        const len = parseInt(this.buffer.slice(1, newline), 10);
        if (len === -1) {
          this.buffer = this.buffer.slice(newline + 2);
          return null;
        }
        const end = newline + 2 + len + 2;
        if (this.buffer.length < end) return undefined;
        const value = this.buffer.slice(newline + 2, newline + 2 + len);
        this.buffer = this.buffer.slice(end);
        return value;
      }
      case "*": {
        const count = parseInt(this.buffer.slice(1, newline), 10);
        if (count === -1) {
          this.buffer = this.buffer.slice(newline + 2);
          return null;
        }
        this.buffer = this.buffer.slice(newline + 2);
        const arr: unknown[] = [];
        for (let i = 0; i < count; i++) {
          const item = this.parseResp();
          if (item === undefined) return undefined;
          arr.push(item);
        }
        return arr;
      }
      default:
        return undefined;
    }
  }

  private command(...args: (string | number)[]): Promise<unknown> {
    return new Promise((resolve, reject) => {
      const cmd = `*${args.length}\r\n${args.map((a) => `$${String(a).length}\r\n${a}\r\n`).join("")}`;
      this.pending.push({ resolve, reject });
      this.socket.write(cmd);
    });
  }

  close(): void {
    this.socket?.end();
  }

  async get(key: string): Promise<string | null> {
    return (await this.command("GET", key)) as string | null;
  }

  async set(key: string, value: string, ttl?: number): Promise<void> {
    if (ttl) {
      await this.command("SET", key, value, "EX", ttl);
    } else {
      await this.command("SET", key, value);
    }
  }

  async del(key: string): Promise<boolean> {
    return ((await this.command("DEL", key)) as number) > 0;
  }

  async exists(key: string): Promise<boolean> {
    return ((await this.command("EXISTS", key)) as number) > 0;
  }

  async incr(key: string): Promise<number> {
    return (await this.command("INCR", key)) as number;
  }

  async decr(key: string): Promise<number> {
    return (await this.command("DECR", key)) as number;
  }

  async incrby(key: string, amount: number): Promise<number> {
    return (await this.command("INCRBY", key, amount)) as number;
  }

  async decrby(key: string, amount: number): Promise<number> {
    return (await this.command("DECRBY", key, amount)) as number;
  }

  async mget(...keys: string[]): Promise<(string | null)[]> {
    return (await this.command("MGET", ...keys)) as (string | null)[];
  }

  async mset(entries: Record<string, string>): Promise<void> {
    const args: string[] = ["MSET"];
    for (const [k, v] of Object.entries(entries)) {
      args.push(k, v);
    }
    await this.command(...args);
  }

  async keys(pattern: string): Promise<string[]> {
    return (await this.command("KEYS", pattern)) as string[];
  }

  async expire(key: string, seconds: number): Promise<boolean> {
    return ((await this.command("EXPIRE", key, seconds)) as number) > 0;
  }

  async ttl(key: string): Promise<number> {
    return (await this.command("TTL", key)) as number;
  }

  async persist(key: string): Promise<boolean> {
    return ((await this.command("PERSIST", key)) as number) > 0;
  }

  async dbsize(): Promise<number> {
    return (await this.command("DBSIZE")) as number;
  }

  async flushdb(): Promise<void> {
    await this.command("FLUSHDB");
  }

  async info(): Promise<string> {
    return (await this.command("INFO")) as string;
  }

  async ping(): Promise<string> {
    return (await this.command("PING")) as string;
  }
}
