/**
 * SquirrelDB TypeScript SDK - Client
 * Generated by sdk-generator v0.1.0
 * DO NOT EDIT MANUALLY
 */

import type { Document, ChangeEvent, ClientMessage, ServerMessage } from "./types";

export interface ConnectOptions {
  reconnect?: boolean;
  reconnectInterval?: number;
  maxReconnectAttempts?: number;
}

type PendingRequest = {
  resolve: (value: unknown) => void;
  reject: (err: Error) => void;
};

/**
 * SquirrelDB WebSocket client
 */
export class SquirrelDB {
  private ws: WebSocket | null = null;
  private url: string;
  private options: Required<ConnectOptions>;
  private pending = new Map<string, PendingRequest>();
  private subscriptions = new Map<string, (change: ChangeEvent) => void>();
  private requestId = 0;
  private reconnectAttempts = 0;
  private closed = false;

  private constructor(url: string, options: ConnectOptions = {}) {
    this.url = url.startsWith("ws://") || url.startsWith("wss://") ? url : `ws://${url}`;
    this.options = {
      reconnect: options.reconnect ?? true,
      reconnectInterval: options.reconnectInterval ?? 1000,
      maxReconnectAttempts: options.maxReconnectAttempts ?? 10,
    };
  }

  /**
   * Connect to SquirrelDB server
   */
  static async connect(url: string, options?: ConnectOptions): Promise<SquirrelDB> {
    const client = new SquirrelDB(url, options);
    await client.connectInternal();
    return client;
  }

  private connectInternal(): Promise<void> {
    return new Promise((resolve, reject) => {
      this.ws = new WebSocket(this.url);

      this.ws.onopen = () => {
        this.reconnectAttempts = 0;
        resolve();
      };

      this.ws.onerror = () => {
        if (this.reconnectAttempts === 0) {
          reject(new Error("Failed to connect"));
        }
      };

      this.ws.onclose = () => {
        if (!this.closed && this.options.reconnect) {
          this.attemptReconnect();
        }
      };

      this.ws.onmessage = (event) => {
        this.handleMessage(event.data);
      };
    });
  }

  private attemptReconnect(): void {
    if (this.reconnectAttempts >= this.options.maxReconnectAttempts) {
      return;
    }
    this.reconnectAttempts++;
    setTimeout(() => {
      this.connectInternal().catch(() => {});
    }, this.options.reconnectInterval);
  }

  private handleMessage(data: string): void {
    const msg = JSON.parse(data) as ServerMessage;

    switch (msg.type) {
      case "Pong":
        break;
      case "Result":
      case "Error":
      case "Subscribed":
      case "Unsubscribed":
      case "Collections": {
        const pending = this.pending.get(msg.id);
        if (pending) {
          this.pending.delete(msg.id);
          if (msg.type === "Error") {
            pending.reject(new Error(msg.message));
          } else {
            pending.resolve(msg);
          }
        }
        break;
      }
      case "Change": {
        const callback = this.subscriptions.get(msg.subscription_id);
        if (callback) {
          callback(msg.change);
        }
        break;
      }
    }
  }

  private send<T>(msg: ClientMessage): Promise<T> {
    return new Promise((resolve, reject) => {
      if (!this.ws || this.ws.readyState !== WebSocket.OPEN) {
        reject(new Error("Not connected"));
        return;
      }
      const id = `req-${++this.requestId}`;
      const message = { ...msg, id } as ClientMessage & { id: string };
      this.pending.set(id, { resolve: resolve as (v: unknown) => void, reject });
      this.ws.send(JSON.stringify(message));
    });
  }

  /**
   * Close the connection
   */
  close(): void {
    this.closed = true;
    this.ws?.close();
  }

  /**
   * Ping the server
   */
  async ping(): Promise<void> {
    this.ws?.send(JSON.stringify({ type: "Ping" }));
  }

  /**
   * List all collections
   */
  async listCollections(): Promise<string[]> {
    const result = await this.send<{ type: "Collections"; collections: string[] }>({
      type: "ListCollections",
      id: "",
    });
    return result.collections;
  }

  /**
   * Execute a query
   */
  async query<T = Document>(query: string): Promise<T[]> {
    const result = await this.send<{ type: "Result"; documents: T[] }>({
      type: "Query",
      id: "",
      query,
    });
    return result.documents;
  }

  /**
   * Insert a document
   */
  async insert(collection: string, data: Record<string, unknown>): Promise<Document> {
    const result = await this.send<{ type: "Result"; documents: Document[] }>({
      type: "Insert",
      id: "",
      collection,
      data,
    });
    return result.documents[0];
  }

  /**
   * Update a document
   */
  async update(collection: string, id: string, data: Record<string, unknown>): Promise<Document> {
    const result = await this.send<{ type: "Result"; documents: Document[] }>({
      type: "Update",
      id: "",
      collection,
      document_id: id,
      data,
    });
    return result.documents[0];
  }

  /**
   * Delete a document
   */
  async delete(collection: string, id: string): Promise<Document> {
    const result = await this.send<{ type: "Result"; documents: Document[] }>({
      type: "Delete",
      id: "",
      collection,
      document_id: id,
    });
    return result.documents[0];
  }

  /**
   * Subscribe to changes
   */
  async subscribe(query: string, callback: (change: ChangeEvent) => void): Promise<string> {
    const result = await this.send<{ type: "Subscribed"; subscription_id: string }>({
      type: "Subscribe",
      id: "",
      query,
    });
    this.subscriptions.set(result.subscription_id, callback);
    return result.subscription_id;
  }

  /**
   * Unsubscribe from changes
   */
  async unsubscribe(subscriptionId: string): Promise<void> {
    await this.send({
      type: "Unsubscribe",
      id: "",
      subscription_id: subscriptionId,
    });
    this.subscriptions.delete(subscriptionId);
  }
}
