/**
 * SquirrelDB TypeScript SDK - Query Builder
 * Generated by sdk-generator v0.1.0
 * DO NOT EDIT MANUALLY
 */

/** Sort direction */
export type SortDirection = "asc" | "desc";

/** Filter condition for a single field */
export interface FilterCondition {
  field: string;
  operator: string;
  value: unknown;
}

/** Sort specification */
export interface SortSpec {
  field: string;
  direction: SortDirection;
}

/** Options for change subscriptions */
export interface ChangesOptions {
  includeInitial?: boolean;
}

/** Structured query object (wire format) */
export interface StructuredQuery {
  table: string;
  filter?: Record<string, unknown>;
  sort?: SortSpec[];
  limit?: number;
  skip?: number;
  changes?: ChangesOptions;
}

/** Field expression for building filter conditions */
export class FieldExpr {
  constructor(private readonly fieldName: string) {}

  /** Equal to */
  eq(value: unknown): FilterCondition {
    return { field: this.fieldName, operator: "$eq", value };
  }

  /** Not equal to */
  ne(value: unknown): FilterCondition {
    return { field: this.fieldName, operator: "$ne", value };
  }

  /** Greater than */
  gt(value: unknown): FilterCondition {
    return { field: this.fieldName, operator: "$gt", value };
  }

  /** Greater than or equal to */
  gte(value: unknown): FilterCondition {
    return { field: this.fieldName, operator: "$gte", value };
  }

  /** Less than */
  lt(value: unknown): FilterCondition {
    return { field: this.fieldName, operator: "$lt", value };
  }

  /** Less than or equal to */
  lte(value: unknown): FilterCondition {
    return { field: this.fieldName, operator: "$lte", value };
  }

  /** Value in array */
  in(values: unknown[]): FilterCondition {
    return { field: this.fieldName, operator: "$in", value: values };
  }

  /** Value not in array */
  notIn(values: unknown[]): FilterCondition {
    return { field: this.fieldName, operator: "$nin", value: values };
  }

  /** String contains substring */
  contains(value: string): FilterCondition {
    return { field: this.fieldName, operator: "$contains", value };
  }

  /** String starts with prefix */
  startsWith(value: string): FilterCondition {
    return { field: this.fieldName, operator: "$startsWith", value };
  }

  /** String ends with suffix */
  endsWith(value: string): FilterCondition {
    return { field: this.fieldName, operator: "$endsWith", value };
  }

  /** Field exists (or not) */
  exists(value: boolean = true): FilterCondition {
    return { field: this.fieldName, operator: "$exists", value };
  }
}

/** Document proxy for fluent field access */
export type DocProxy = {
  [field: string]: FieldExpr;
};

function createDocProxy(): DocProxy {
  return new Proxy({} as DocProxy, {
    get(_, prop: string) {
      return new FieldExpr(prop);
    },
  });
}

/** Query builder for constructing SquirrelDB queries */
export class QueryBuilder {
  private readonly tableName: string;
  private filters: FilterCondition[] = [];
  private sorts: SortSpec[] = [];
  private limitValue?: number;
  private skipValue?: number;
  private changesOpts?: ChangesOptions;

  constructor(tableName: string) {
    this.tableName = tableName;
  }

  /** Add filter conditions using callback or object */
  find(
    condition: FilterCondition | FilterCondition[] | ((doc: DocProxy) => FilterCondition | FilterCondition[])
  ): QueryBuilder {
    if (typeof condition === "function") {
      const result = condition(createDocProxy());
      if (Array.isArray(result)) {
        this.filters.push(...result);
      } else {
        this.filters.push(result);
      }
    } else if (Array.isArray(condition)) {
      this.filters.push(...condition);
    } else {
      this.filters.push(condition);
    }
    return this;
  }

  /** Add sort specification */
  sort(fieldName: string, direction: SortDirection = "asc"): QueryBuilder {
    this.sorts.push({ field: fieldName, direction });
    return this;
  }

  /** Set maximum number of results */
  limit(n: number): QueryBuilder {
    this.limitValue = n;
    return this;
  }

  /** Set number of results to skip */
  skip(n: number): QueryBuilder {
    this.skipValue = n;
    return this;
  }

  /** Subscribe to changes */
  changes(options: ChangesOptions = { includeInitial: true }): QueryBuilder {
    this.changesOpts = options;
    return this;
  }

  /** Compile to structured query object */
  compileStructured(): StructuredQuery {
    const query: StructuredQuery = {
      table: this.tableName,
    };

    if (this.filters.length > 0) {
      query.filter = this.buildFilterObject();
    }

    if (this.sorts.length > 0) {
      query.sort = this.sorts;
    }

    if (this.limitValue !== undefined) {
      query.limit = this.limitValue;
    }

    if (this.skipValue !== undefined) {
      query.skip = this.skipValue;
    }

    if (this.changesOpts !== undefined) {
      query.changes = this.changesOpts;
    }

    return query;
  }

  /** Compile to JSON string */
  compile(): string {
    return JSON.stringify(this.compileStructured());
  }

  private buildFilterObject(): Record<string, unknown> {
    const filterObj: Record<string, Record<string, unknown>> = {};

    for (const cond of this.filters) {
      if (!filterObj[cond.field]) {
        filterObj[cond.field] = {};
      }
      filterObj[cond.field][cond.operator] = cond.value;
    }

    return filterObj;
  }
}

/** Create a new query builder for a table */
export function table(name: string): QueryBuilder {
  return new QueryBuilder(name);
}

/** Create a field expression for filtering */
export function field(name: string): FieldExpr {
  return new FieldExpr(name);
}

/** Combine conditions with AND */
export function and(...conditions: FilterCondition[]): FilterCondition {
  return {
    field: "$and",
    operator: "$and",
    value: conditions,
  };
}

/** Combine conditions with OR */
export function or(...conditions: FilterCondition[]): FilterCondition {
  return {
    field: "$or",
    operator: "$or",
    value: conditions,
  };
}

/** Negate a condition */
export function not(condition: FilterCondition): FilterCondition {
  return {
    field: "$not",
    operator: "$not",
    value: condition,
  };
}
