/**
 * SquirrelDB TypeScript SDK - Storage (S3-compatible)
 * Generated by sdk-generator v0.1.0
 * DO NOT EDIT MANUALLY
 */

import type { Bucket, StorageObject } from "./types";

export interface StorageOptions {
  endpoint: string;
  accessKeyId?: string;
  secretAccessKey?: string;
  region?: string;
}

export class StorageError extends Error {
  constructor(
    public status: number,
    message: string
  ) {
    super(message);
    this.name = "StorageError";
  }
}

/**
 * S3-compatible storage client
 */
export class Storage {
  private endpoint: string;
  private accessKeyId?: string;
  private secretAccessKey?: string;
  private region: string;

  private constructor(options: StorageOptions) {
    this.endpoint = options.endpoint.replace(/\/$/, "");
    this.accessKeyId = options.accessKeyId;
    this.secretAccessKey = options.secretAccessKey;
    this.region = options.region ?? "us-east-1";
  }

  /**
   * Create a new storage client
   */
  static connect(options: StorageOptions): Storage {
    return new Storage(options);
  }

  private async request(
    method: string,
    path: string,
    body?: Uint8Array | string,
    headers: Record<string, string> = {}
  ): Promise<Response> {
    const url = `${this.endpoint}${path}`;
    const reqHeaders: Record<string, string> = { ...headers };

    if (this.accessKeyId && this.secretAccessKey) {
      reqHeaders["x-amz-access-key-id"] = this.accessKeyId;
    }

    const response = await fetch(url, {
      method,
      headers: reqHeaders,
      body: body as BodyInit | undefined,
    });

    if (!response.ok) {
      const text = await response.text();
      throw new StorageError(response.status, text);
    }

    return response;
  }

  async listBuckets(): Promise<Bucket[]> {
    const response = await this.request("GET", "/");
    const text = await response.text();
    const matches = text.matchAll(/<Name>([^<]+)<\/Name>/g);
    return Array.from(matches, (m) => ({
      name: m[1],
      created_at: new Date().toISOString(),
    }));
  }

  async createBucket(name: string): Promise<void> {
    await this.request("PUT", `/${name}`);
  }

  async deleteBucket(name: string): Promise<void> {
    await this.request("DELETE", `/${name}`);
  }

  async bucketExists(name: string): Promise<boolean> {
    try {
      await this.request("HEAD", `/${name}`);
      return true;
    } catch {
      return false;
    }
  }

  async listObjects(bucket: string, prefix?: string, maxKeys?: number): Promise<StorageObject[]> {
    const params = new URLSearchParams();
    if (prefix) params.set("prefix", prefix);
    if (maxKeys) params.set("max-keys", String(maxKeys));
    const query = params.toString() ? `?${params}` : "";

    const response = await this.request("GET", `/${bucket}${query}`);
    const text = await response.text();
    const matches = text.matchAll(/<Key>([^<]+)<\/Key>.*?<Size>(\d+)<\/Size>.*?<ETag>([^<]+)<\/ETag>/gs);

    return Array.from(matches, (m) => ({
      key: m[1],
      size: parseInt(m[2], 10),
      etag: m[3].replace(/"/g, ""),
      last_modified: new Date().toISOString(),
      content_type: null,
    }));
  }

  async getObject(bucket: string, key: string): Promise<Uint8Array> {
    const response = await this.request("GET", `/${bucket}/${key}`);
    return new Uint8Array(await response.arrayBuffer());
  }

  async putObject(
    bucket: string,
    key: string,
    data: Uint8Array | string,
    contentType?: string
  ): Promise<string> {
    const headers: Record<string, string> = {};
    if (contentType) headers["content-type"] = contentType;

    const response = await this.request("PUT", `/${bucket}/${key}`, data, headers);
    return response.headers.get("etag")?.replace(/"/g, "") ?? "";
  }

  async deleteObject(bucket: string, key: string): Promise<void> {
    await this.request("DELETE", `/${bucket}/${key}`);
  }

  async objectExists(bucket: string, key: string): Promise<boolean> {
    try {
      await this.request("HEAD", `/${bucket}/${key}`);
      return true;
    } catch {
      return false;
    }
  }
}
