/**
 * SquirrelDB TypeScript SDK - Types
 * Generated by sdk-generator v0.1.0
 * DO NOT EDIT MANUALLY
 */

/**
 * A document stored in SquirrelDB
 */
export interface Document {
  /** Unique document identifier */
  id: string;
  /** Collection name */
  collection: string;
  /** Document data */
  data: Record<string, unknown>;
  /** ISO 8601 creation timestamp */
  created_at: string;
  /** ISO 8601 update timestamp */
  updated_at: string;
}

/**
 * A change event from a subscription
 */
export interface ChangeEvent {
  /** Type of change */
  type: ChangeType;
  /** Document for initial events */
  document: Document | null;
  /** Previous value for update/delete */
  old: unknown | null;
  /** New document for insert/update */
  new: Document | null;
}

/**
 * Storage bucket
 */
export interface Bucket {
  /**  */
  name: string;
  /**  */
  created_at: string;
}

/**
 * Object in storage
 */
export interface StorageObject {
  /**  */
  key: string;
  /**  */
  size: number;
  /**  */
  etag: string;
  /**  */
  last_modified: string;
  /**  */
  content_type: string | null;
}


export type ChangeType = "initial" | "insert" | "update" | "delete";

export type MessageType = "Ping" | "Pong" | "Query" | "Insert" | "Update" | "Delete" | "Subscribe" | "Unsubscribe" | "Result" | "Error" | "Subscribed" | "Unsubscribed" | "Change" | "ListCollections" | "Collections";


/**
 * Client message types
 */
export type ClientMessage =
  | { type: "Ping" }
  | { type: "Query"; id: string; query: string }
  | { type: "Insert"; id: string; collection: string; data: Record<string, unknown> }
  | { type: "Update"; id: string; collection: string; document_id: string; data: Record<string, unknown> }
  | { type: "Delete"; id: string; collection: string; document_id: string }
  | { type: "Subscribe"; id: string; query: string }
  | { type: "Unsubscribe"; id: string; subscription_id: string }
  | { type: "ListCollections"; id: string };

/**
 * Server message types
 */
export type ServerMessage =
  | { type: "Pong" }
  | { type: "Result"; id: string; documents: Document[] }
  | { type: "Error"; id: string; message: string }
  | { type: "Subscribed"; id: string; subscription_id: string }
  | { type: "Unsubscribed"; id: string }
  | { type: "Change"; subscription_id: string; change: ChangeEvent }
  | { type: "Collections"; id: string; collections: string[] };
